#! /bin/sh
#
# $Id: nvidia,v 1.14 2008/03/06 23:42:01 mjk Exp $
#
# chkconfig: 5 01 01
# description: Install NVIDIA driver
#
# @Copyright@
# 
# 				Rocks(r)
# 		         www.rocksclusters.org
# 		            version 5.0 (V)
# 
# Copyright (c) 2000 - 2008 The Regents of the University of California.
# All rights reserved.	
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
# 
# 1. Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright
# notice unmodified and in its entirety, this list of conditions and the
# following disclaimer in the documentation and/or other materials provided 
# with the distribution.
# 
# 3. All advertising and press materials, printed or electronic, mentioning
# features or use of this software must display the following acknowledgement: 
# 
# 	"This product includes software developed by the Rocks(r)
# 	Cluster Group at the San Diego Supercomputer Center at the
# 	University of California, San Diego and its contributors."
# 
# 4. Except as permitted for the purposes of acknowledgment in paragraph 3,
# neither the name or logo of this software nor the names of its
# authors may be used to endorse or promote products derived from this
# software without specific prior written permission.  The name of the
# software includes the following terms, and any derivatives thereof:
# "Rocks", "Rocks Clusters", and "Avalanche Installer".  For licensing of 
# the associated name, interested parties should contact Technology 
# Transfer & Intellectual Property Services, University of California, 
# San Diego, 9500 Gilman Drive, Mail Code 0910, La Jolla, CA 92093-0910, 
# Ph: (858) 534-5815, FAX: (858) 534-7345, E-MAIL:invent@ucsd.edu
# 
# THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS''
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# 
# @Copyright@
#
# $Log: nvidia,v $
# Revision 1.14  2008/03/06 23:42:01  mjk
# copyright storm on
#
# Revision 1.13  2007/08/10 23:38:55  mjk
# *** empty log message ***
#
# Revision 1.12  2007/06/23 04:04:04  mjk
# mars hill copyright
#
# Revision 1.11  2006/09/11 22:50:36  mjk
# monkey face copyright
#
# Revision 1.10  2006/08/10 00:12:13  mjk
# 4.2 copyright
#
# Revision 1.9  2005/10/12 18:11:17  mjk
# final copyright for 4.1
#
# Revision 1.8  2005/09/16 01:04:56  mjk
# updated copyright
#
# Revision 1.7  2005/05/24 21:24:08  mjk
# update copyright, release is not any closer
#
# Revision 1.6  2005/04/21 01:28:21  bruno
# update for xorg (instead of XFree86)
#
# Revision 1.5  2005/01/19 00:38:55  mjk
# don't build driver unless in rl 5
#
# Revision 1.4  2004/10/08 23:05:25  mjk
# *** empty log message ***
#
# Revision 1.3  2004/10/06 23:09:56  mjk
# open up the framebuffer for chromium to work
#
# Revision 1.2  2004/07/16 23:47:33  mjk
# *** empty log message ***
#
# Revision 1.1  2004/07/16 16:55:12  mjk
# *** empty log message ***
#

. /etc/init.d/functions

case "$1" in
    start)
	if [ -x /usr/bin/nvidia-xconfig ]; then
		exit 0
	fi
        action $"Loading nVidia Driver" /opt/viz/drivers/nvidia/install-driver
        RETVAL=$?
        ;;
    stop)
        ;;
    restart)
        $0 stop
        $0 start
        RETVAL=$?
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $RETVAL
