#!/bin/bash
#
# $Id: Xclients,v 1.25 2008/10/18 00:56:20 mjk Exp $
#
# @Copyright@
# 
# 				Rocks(r)
# 		         www.rocksclusters.org
# 		           version 5.1  (VI)
# 
# Copyright (c) 2000 - 2008 The Regents of the University of California.
# All rights reserved.	
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
# 
# 1. Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright
# notice unmodified and in its entirety, this list of conditions and the
# following disclaimer in the documentation and/or other materials provided 
# with the distribution.
# 
# 3. All advertising and press materials, printed or electronic, mentioning
# features or use of this software must display the following acknowledgement: 
# 
# 	"This product includes software developed by the Rocks(r)
# 	Cluster Group at the San Diego Supercomputer Center at the
# 	University of California, San Diego and its contributors."
# 
# 4. Except as permitted for the purposes of acknowledgment in paragraph 3,
# neither the name or logo of this software nor the names of its
# authors may be used to endorse or promote products derived from this
# software without specific prior written permission.  The name of the
# software includes the following terms, and any derivatives thereof:
# "Rocks", "Rocks Clusters", and "Avalanche Installer".  For licensing of 
# the associated name, interested parties should contact Technology 
# Transfer & Intellectual Property Services, University of California, 
# San Diego, 9500 Gilman Drive, Mail Code 0910, La Jolla, CA 92093-0910, 
# Ph: (858) 534-5815, FAX: (858) 534-7345, E-MAIL:invent@ucsd.edu
# 
# THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS''
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# 
# @Copyright@
#
# $Log: Xclients,v $
# Revision 1.25  2008/10/18 00:56:20  mjk
# copyright 5.1
#
# Revision 1.24  2008/03/06 23:42:01  mjk
# copyright storm on
#
# Revision 1.23  2007/09/19 13:28:58  mjk
# Swiss Viss
#
# Revision 1.22  2007/09/04 22:47:34  mjk
# move dmxrc generation to rcl
#
# Revision 1.21  2007/08/21 19:24:13  mjk
# *** empty log message ***
#
# Revision 1.20  2007/07/27 17:30:22  mjk
# checkpoint
#
# Revision 1.19  2007/07/09 17:52:34  mjk
# dbreport is dead
#
# Revision 1.18  2007/06/23 04:04:05  mjk
# mars hill copyright
#
# Revision 1.17  2006/09/11 22:50:40  mjk
# monkey face copyright
#
# Revision 1.16  2006/08/10 00:12:15  mjk
# 4.2 copyright
#
# Revision 1.15  2006/06/29 19:56:51  mjk
# added viz-reconfig
#
# Revision 1.14  2006/02/16 03:56:14  mjk
# XDMX started by fvwm menu
#
# Revision 1.13  2006/02/14 20:49:10  mjk
# - Added FlightGear and prereqs
# - Added FVWM (use instead of MWM)
# - Autologin of viz user on frontend does not start XDMX
# - More screen blanking nonsense
#
# Revision 1.12  2006/02/14 01:04:06  mjk
# switch to fvwm
#
# Revision 1.11  2005/10/12 18:11:19  mjk
# final copyright for 4.1
#
# Revision 1.10  2005/09/16 01:04:57  mjk
# updated copyright
#
# Revision 1.9  2005/06/02 23:01:17  mjk
# xset only on backend tiles
#
# Revision 1.8  2005/05/31 23:21:12  mjk
# more tweaks to stop screen blanking
#
# Revision 1.7  2005/05/31 18:47:00  mjk
# no blank = 0
#
# Revision 1.6  2005/05/24 21:24:09  mjk
# update copyright, release is not any closer
#
# Revision 1.5  2005/04/26 21:30:08  bruno
# reall turn off video blanking
#
# Revision 1.4  2005/04/21 19:37:05  bruno
# don't set the .Xauthority file -- this causes permission problem when trying
# to login as a user
#
# Revision 1.3  2005/02/22 19:50:39  mjk
# *** empty log message ***
#
# Revision 1.2  2004/09/08 21:31:21  mjk
# no screen blanking
#
# Revision 1.1  2004/09/08 20:09:32  mjk
# added rocks-viz, moved stuff from common to master node
#

if [ "$DISPLAY" = ":0" ]; then
	exec /etc/X11/xinit/Xclients
fi

/opt/viz/bin/dmx_config > ~/.dmx_config

xset -dpms
xset s off
xset s noblank

xsetroot -solid '#5477A0'

exec $WINDOWMANAGER
