#!/opt/rocks/bin/python
#
# $Id: Xclients,v 1.28 2011/07/23 02:31:38 phil Exp $
#
# @Copyright@
# 
# 				Rocks(r)
# 		         www.rocksclusters.org
# 		         version 5.4.3 (Viper)
# 
# Copyright (c) 2000 - 2011 The Regents of the University of California.
# All rights reserved.	
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
# 
# 1. Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright
# notice unmodified and in its entirety, this list of conditions and the
# following disclaimer in the documentation and/or other materials provided 
# with the distribution.
# 
# 3. All advertising and press materials, printed or electronic, mentioning
# features or use of this software must display the following acknowledgement: 
# 
# 	"This product includes software developed by the Rocks(r)
# 	Development Team at the San Diego Supercomputer Center at the
# 	University of California, San Diego and its contributors."
# 
# 4. Except as permitted for the purposes of acknowledgment in paragraph 3,
# neither the name or logo of this software nor the names of its
# authors may be used to endorse or promote products derived from this
# software without specific prior written permission.  The name of the
# software includes the following terms, and any derivatives thereof:
# "Rocks", "Rocks Clusters", and "Avalanche Installer".  For licensing of 
# the associated name, interested parties should contact Technology 
# Transfer & Intellectual Property Services, University of California, 
# San Diego, 9500 Gilman Drive, Mail Code 0910, La Jolla, CA 92093-0910, 
# Ph: (858) 534-5815, FAX: (858) 534-7345, E-MAIL:invent@ucsd.edu
# 
# THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS''
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# 
# @Copyright@
#
# $Log: Xclients,v $
# Revision 1.28  2011/07/23 02:31:38  phil
# Viper Copyright
#
# Revision 1.27  2010/09/07 23:53:28  bruno
# star power for gb
#
# Revision 1.26  2009/05/09 23:04:07  mjk
# - tile-banner use rand seed to sync the logo on multi-head nodes
# - Xclients is python, and disables screensaver (again)
# - xorg.conf on tiles turns off DPMS
# - tiles come up in a completely probed mode (resolution not set)
# - all else is just broken and this is a check point
#
# Revision 1.25  2009/05/07 23:28:01  mjk
# now in python
#
# Revision 1.24  2009/05/01 19:07:31  mjk
# chimi con queso
#
# Revision 1.23  2008/10/18 00:56:20  mjk
# copyright 5.1
#
# Revision 1.22  2008/03/06 23:42:02  mjk
# copyright storm on
#
# Revision 1.21  2008/01/14 22:03:47  bruno
# tweaks for V
#
# Revision 1.20  2007/09/19 12:46:31  mjk
# *** empty log message ***
#
# Revision 1.19  2007/07/30 23:11:29  mjk
# beta time
#
# Revision 1.18  2007/07/27 17:30:22  mjk
# checkpoint
#
# Revision 1.17  2007/06/23 04:04:05  mjk
# mars hill copyright
#
# Revision 1.16  2006/12/20 22:12:44  bruno
# this is not the cursor you are looking for.
#
# on tile nodes, make the mouse pointer cursor invisible.
#
# Revision 1.15  2006/09/11 22:50:41  mjk
# monkey face copyright
#
# Revision 1.14  2006/08/10 00:12:16  mjk
# 4.2 copyright
#
# Revision 1.13  2006/06/27 00:30:03  mjk
# - chromium reads config from DMX not from DB now
# - DMX config fixes for crazy Kim layout
# - Tile background color is a hash of the hostname
#
# Revision 1.12  2006/02/14 01:04:06  mjk
# switch to fvwm
#
# Revision 1.11  2006/01/11 23:04:33  mjk
# fix mwm
#
# Revision 1.10  2006/01/10 15:56:50  mjk
# Settings from EVL to disable screen blanking
#
# Revision 1.9  2005/10/12 18:11:19  mjk
# final copyright for 4.1
#
# Revision 1.8  2005/09/16 01:04:57  mjk
# updated copyright
#
# Revision 1.7  2005/06/02 23:00:20  mjk
# more xset madness
#
# Revision 1.6  2005/05/24 21:24:09  mjk
# update copyright, release is not any closer
#
# Revision 1.5  2005/04/26 21:30:10  bruno
# reall turn off video blanking
#
# Revision 1.4  2005/04/21 20:41:17  bruno
# really turn off video blanking
#
# Revision 1.3  2004/10/08 23:05:25  mjk
# *** empty log message ***
#
# Revision 1.2  2004/10/07 22:53:25  mjk
# Added tile-banner to label nodes by hostname
# Viz user profile calls tile-banner
#
# Revision 1.1  2004/09/11 03:36:41  mjk
# *** empty log message ***
#

import os
import popen2
import string
import time

os.system('chmod a+rw /dev/nvidia*')
os.system('chmod a+rw /dev/dsp*')
os.system('chmod a+rw /dev/audio*')

os.system('xset s 0 0')
os.system('xset s noexpose')
os.system('xset s noblank')
os.system('xset s off')
os.system('xsetroot -cursor /opt/viz/etc/invisible-cursor.xbm \
	/opt/viz/etc/invisible-cursor.xbm')

displays = []
r,w = popen2.popen2('nvidia-settings -q screens')
for line in r.readlines():
	if line.find('[') != -1:
		displays.append(line.split()[1])

for display in displays:
	os.environ['DISPLAY'] = display
	os.system('xhost +')
	os.system('/opt/viz/sbin/tile-banner &')

while True:
	time.sleep(1)
	os.system('xset s reset')
